language: python
python:
    - 3.4
install:
    - pip install -r requirements.txt
    - pip install coveralls
    - pip install pytest-cov

script:
  coverage run --source=my_app manage.py test_cases
after_success:
  coveralls
